resources:
  - ../../base
patches:
  - path: replica_count.yaml
  - path: deployment_patch.yaml
labels:
  - pairs:
      env: production  # Label applied to every resource
    includeSelectors: true
namePrefix: prod-  # Prefix added to the name of all resources
