resources:
  - ../../base
patches:
  - replica_count.yaml
  - deployment_patch.yaml
labels:
  env: production  # Label applied to every resource
namePrefix: prod-  # Prefix added to the name of all resources