bases:
  - ../../base # Path to the base configuration directory
patchesStrategicMerge:
  - replica_count.yaml # List of patches to apply to the base resources
commonLabels:
  env: staging  # Label applied to every resource
namePrefix: staging-  # Prefix added to the name of all resources