resources:
  - ../../base
patches:
  - replica_count.yaml
  - deployment_patch.yaml
labels:
  - name: env
    value: development # Label applied to every resource
namePrefix: dev-  # Prefix added to the name of all resources